// front/src/views/ReadView.tsx
import React, { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { container } from 'tsyringe'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import Post from '@/entity/post/Post'
import CommentList from '@/entity/comment/CommentList'
import CommentEntity from '@/entity/comment/Comment'
import type HttpError from '@/http/HttpError'
import type UserProfile from '@/entity/user/UserProfile'
import PostRepository from '@/repository/PostRepository'
import AccountRepository from '@/repository/AccountRepository'
import Comments from '@/components/Comments'

const POST_REPOSITORY = container.resolve(PostRepository)
const USER_REPOSITORY = container.resolve(AccountRepository)

export default function ReadView() {
  const { postId } = useParams<{ postId: string }>()
  const navigate = useNavigate()
  const [post, setPost] = useState<Post>(new Post())
  const [commentList, setCommentList] = useState<CommentList<CommentEntity>>(new CommentList<CommentEntity>())
  const [profile, setProfile] = useState<UserProfile | null>(null)

  function getPost() {
    POST_REPOSITORY.get(Number(postId))
      .then((p: Post) => {
        setPost(p)
        const cl = new CommentList<CommentEntity>()
        cl.setComments(p.comments)
        setCommentList(cl)
      })
      .catch((e) => console.error(e))
  }

  function remove() {
    if (!window.confirm('정말로 삭제하시겠습니까?')) return
    POST_REPOSITORY.delete(Number(postId))
      .then(() => {
        alert('삭제되었습니다.')
        navigate('/blog')
      })
      .catch((error: HttpError) => alert(error.toString()))
  }

  useEffect(() => {
    getPost()
    USER_REPOSITORY.getProfile()
      .then(setProfile)
      .catch(() => {/* 비로그인 */})
  }, [postId])

  const isAdmin = profile?.isAdmin() ?? false

  return (
    <div className="max-w-2xl mx-auto">
      {/* Back */}
      <button
        onClick={() => navigate('/blog')}
        className="flex items-center gap-1 text-sm text-slate-400 hover:text-slate-700 mb-8 transition-colors"
      >
        ← 목록으로
      </button>

      {/* Article */}
      <article className="bg-white rounded-2xl border border-slate-100 shadow-sm p-8">
        <header className="mb-8 pb-6 border-b border-slate-100">
          <h1 className="text-3xl font-bold text-slate-800 tracking-tight leading-tight">
            {post.title}
          </h1>
          <p className="text-xs text-slate-400 mt-3">
            {post.getDisplayRegDate()}
            {post.author && <span className="ml-3 font-medium text-slate-500">{post.author}</span>}
          </p>
        </header>

        <div className="prose max-w-none">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {post.content}
          </ReactMarkdown>
        </div>

        {/* Actions — 어드민만 표시 */}
        {isAdmin && (
          <footer className="mt-8 pt-6 border-t border-slate-100 flex justify-end gap-4">
            <button
              className="text-xs text-slate-400 hover:text-slate-700 transition-colors"
              onClick={() => navigate(`/blog/edit/${postId}`)}
            >
              수정
            </button>
            <button
              className="text-xs text-red-400 hover:text-red-600 transition-colors"
              onClick={remove}
            >
              삭제
            </button>
          </footer>
        )}
      </article>

      {/* Comments */}
      <div className="mt-6">
        <Comments commentList={commentList} postId={Number(postId)} onRefresh={getPost} />
      </div>
    </div>
  )
}

// front/src/views/ReadView.vue
<script setup lang="ts">
import Comments from '@/components/Comments.vue'
import { default as CommentList } from '@/entity/comment/CommentList'
import Post from '@/entity/post/Post'
import type HttpError from '@/http/HttpError'
import PostRepository from '@/repository/PostRepository'
import { ElMessage, ElMessageBox } from 'element-plus'
import { container } from 'tsyringe'
import { onMounted, reactive } from 'vue'
import { useRouter } from 'vue-router'

const props = defineProps<{
  postId: number
}>()

const POST_REPOSITORY = container.resolve(PostRepository)

type StateType = {
  post: Post
  commentList: CommentList<Comment>
}

const state = reactive<StateType>({
  post: new Post(),
  commentList: new CommentList<Comment>()
})

function getPost() {
  POST_REPOSITORY.get(props.postId)
    .then((post: Post) => {
      state.post = post
      state.commentList = new CommentList<Comment>()
      state.commentList.setComments(post.comments, post.comments.length)
    })
    .catch((e) => {
      console.error(e)
    })
}

const router = useRouter()

function remove() {
  ElMessageBox.confirm('정말로 삭제하시겠습니까?', 'Warning', {
    title: '삭제',
    confirmButtonText: '삭제',
    cancelButtonText: '취소',
    type: 'warning'
  }).then(() => {
    POST_REPOSITORY.delete(props.postId)
      .then(() => {
        ElMessage({ type: 'success', message: '성공적으로 삭제되었습니다.' })
        router.back()
      })
      .catch((error: HttpError) => {
        ElMessage({ type: 'error', message: error.toString() })
      })
  })
}

function update() {
  router.push(`/edit/${props.postId}`)
}

onMounted(() => {
  getPost()
})
</script>

<template>
  <el-row>
    <el-col :span="22" :offset="1">
      <div class="title">{{ state.post.title }}</div>
    </el-col>
  </el-row>

  <el-row>
    <el-col :span="10" :offset="7">
      <div class="title">
        <div class="regDate">Posted on {{ state.post.getDisplayRegDate() }}</div>
      </div>
    </el-col>
  </el-row>

  <el-row>
    <el-col>
      <div class="content">
        {{ state.post.content }}
      </div>

      <div class="footer">
        <div class="edit" @click="update()">수정</div>
        <div class="delete" @click="remove()">삭제</div>
      </div>
    </el-col>
  </el-row>

  <Comments :commentList="state.commentList" :postId="props.postId" />
</template>

<style scoped lang="scss">
.title {
  font-size: 1.8rem;
  font-weight: 400;
  text-align: center;
}

.regDate {
  margin-top: 0.5rem;
  font-size: 0.78rem;
  font-weight: 300;
}

.content {
  margin-top: 1.88rem;
  font-weight: 300;

  word-break: break-all;
  white-space: break-spaces;
  line-height: 1.4;
  min-height: 5rem;
}

hr {
  border-color: #f9f9f9;
  margin: 1.2rem 0;
}

.footer {
  margin-top: 1rem;
  display: flex;
  font-size: 0.78rem;
  justify-content: flex-end;
  gap: 0.8rem;

  .delete {
    color: red;
  }
}

.comments {
  margin-top: 4.8rem;
}
</style>
